"""create_skill_gaps_table

Revision ID: 481d20022761
Revises: 88714b258f40
Create Date: 2026-09-12 11:57:28.978531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '481d20022761'
down_revision: Union[str, Sequence[str], None] = '88714b258f40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_gaps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('competency_id', sa.UUID(), nullable=False),
    sa.Column('current_score', sa.Float(), nullable=False),
    sa.Column('required_score', sa.Float(), nullable=False),
    sa.Column('gap_score', sa.Float(), nullable=False),
    sa.Column('current_level_id', sa.UUID(), nullable=True),
    sa.Column('required_level_id', sa.UUID(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('confidence_flag', sa.String(length=30), nullable=False),
    sa.Column('criticality', sa.String(length=20), nullable=False),
    sa.Column('task_relevance', sa.String(length=20), nullable=False),
    sa.Column('mission_urgency', sa.String(length=20), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('priority_level', sa.String(length=20), nullable=False),
    sa.Column('role_relevance', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['current_level_id'], ['proficiency_levels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['required_level_id'], ['proficiency_levels.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'competency_id', name='uq_skill_gaps_employee_competency')
    )
    op.create_index(op.f('ix_skill_gaps_competency_id'), 'skill_gaps', ['competency_id'], unique=False)
    op.create_index(op.f('ix_skill_gaps_employee_id'), 'skill_gaps', ['employee_id'], unique=False)
    op.add_column('competency_requirements', sa.Column('mission_urgency', sa.String(length=20), server_default='MEDIUM', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competency_requirements', 'mission_urgency')
    op.drop_index(op.f('ix_skill_gaps_employee_id'), table_name='skill_gaps')
    op.drop_index(op.f('ix_skill_gaps_competency_id'), table_name='skill_gaps')
    op.drop_table('skill_gaps')
    # ### end Alembic commands ###
