"""create_learning_recommendation_tables

Revision ID: 4b20f7e49d10
Revises: 481d20022761
Create Date: 2026-09-12 12:27:50.159456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b20f7e49d10'
down_revision: Union[str, Sequence[str], None] = '481d20022761'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_item_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('difficulty', sa.String(length=50), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('format', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('prerequisites', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source_mode', sa.String(length=20), nullable=False),
    sa.Column('item_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_items_provider'), 'learning_items', ['provider'], unique=False)
    op.create_index(op.f('ix_learning_items_provider_item_id'), 'learning_items', ['provider_item_id'], unique=False)
    op.create_table('learning_item_competencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('learning_item_id', sa.UUID(), nullable=False),
    sa.Column('competency_id', sa.UUID(), nullable=False),
    sa.Column('coverage_level', sa.String(length=50), nullable=False),
    sa.Column('learning_outcome', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['learning_item_id'], ['learning_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_item_competencies_competency_id'), 'learning_item_competencies', ['competency_id'], unique=False)
    op.create_index(op.f('ix_learning_item_competencies_learning_item_id'), 'learning_item_competencies', ['learning_item_id'], unique=False)
    op.create_table('learning_paths',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('target_role_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_role_id'], ['job_roles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_paths_employee_id'), 'learning_paths', ['employee_id'], unique=False)
    op.create_table('learning_path_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('learning_path_id', sa.UUID(), nullable=False),
    sa.Column('learning_item_id', sa.UUID(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('target_competency_id', sa.UUID(), nullable=False),
    sa.Column('estimated_duration', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['learning_item_id'], ['learning_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['learning_path_id'], ['learning_paths.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_competency_id'], ['competencies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_path_items_learning_item_id'), 'learning_path_items', ['learning_item_id'], unique=False)
    op.create_index(op.f('ix_learning_path_items_learning_path_id'), 'learning_path_items', ['learning_path_id'], unique=False)
    op.create_table('learning_recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('learning_item_id', sa.UUID(), nullable=False),
    sa.Column('target_competency_id', sa.UUID(), nullable=False),
    sa.Column('gap_id', sa.UUID(), nullable=True),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('matched_competencies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('priority_level', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recommendation_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gap_id'], ['skill_gaps.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['learning_item_id'], ['learning_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_competency_id'], ['competencies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_recommendations_employee_id'), 'learning_recommendations', ['employee_id'], unique=False)
    op.create_index(op.f('ix_learning_recommendations_gap_id'), 'learning_recommendations', ['gap_id'], unique=False)
    op.create_index(op.f('ix_learning_recommendations_learning_item_id'), 'learning_recommendations', ['learning_item_id'], unique=False)
    op.create_index(op.f('ix_learning_recommendations_target_competency_id'), 'learning_recommendations', ['target_competency_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learning_recommendations_target_competency_id'), table_name='learning_recommendations')
    op.drop_index(op.f('ix_learning_recommendations_learning_item_id'), table_name='learning_recommendations')
    op.drop_index(op.f('ix_learning_recommendations_gap_id'), table_name='learning_recommendations')
    op.drop_index(op.f('ix_learning_recommendations_employee_id'), table_name='learning_recommendations')
    op.drop_table('learning_recommendations')
    op.drop_index(op.f('ix_learning_path_items_learning_path_id'), table_name='learning_path_items')
    op.drop_index(op.f('ix_learning_path_items_learning_item_id'), table_name='learning_path_items')
    op.drop_table('learning_path_items')
    op.drop_index(op.f('ix_learning_paths_employee_id'), table_name='learning_paths')
    op.drop_table('learning_paths')
    op.drop_index(op.f('ix_learning_item_competencies_learning_item_id'), table_name='learning_item_competencies')
    op.drop_index(op.f('ix_learning_item_competencies_competency_id'), table_name='learning_item_competencies')
    op.drop_table('learning_item_competencies')
    op.drop_index(op.f('ix_learning_items_provider_item_id'), table_name='learning_items')
    op.drop_index(op.f('ix_learning_items_provider'), table_name='learning_items')
    op.drop_table('learning_items')
    # ### end Alembic commands ###
