"""create_assessment_and_evidence_tables

Revision ID: 88714b258f40
Revises: b10fc32ecd4c
Create Date: 2026-09-12 11:33:47.246909

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '88714b258f40'
down_revision: str | Sequence[str] | None = 'b10fc32ecd4c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('assessment_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assessment_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_score', sa.Float(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_attempts_assessment_id'), 'assessment_attempts', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_assessment_attempts_employee_id'), 'assessment_attempts', ['employee_id'], unique=False)
    op.create_table('assessment_competencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('competency_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'competency_id', name='uq_assessment_competency')
    )
    op.create_index(op.f('ix_assessment_competencies_assessment_id'), 'assessment_competencies', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_assessment_competencies_competency_id'), 'assessment_competencies', ['competency_id'], unique=False)
    op.create_table('assessment_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('competency_id', sa.UUID(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correct_option', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_questions_assessment_id'), 'assessment_questions', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_assessment_questions_competency_id'), 'assessment_questions', ['competency_id'], unique=False)
    op.create_table('competency_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('competency_id', sa.UUID(), nullable=False),
    sa.Column('evidence_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=True),
    sa.Column('raw_value', sa.Float(), nullable=False),
    sa.Column('normalized_score', sa.Float(), nullable=False),
    sa.Column('weight_used', sa.Float(), nullable=False),
    sa.Column('contribution', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competency_evidence_competency_id'), 'competency_evidence', ['competency_id'], unique=False)
    op.create_index(op.f('ix_competency_evidence_employee_id'), 'competency_evidence', ['employee_id'], unique=False)
    op.create_index(op.f('ix_competency_evidence_evidence_type'), 'competency_evidence', ['evidence_type'], unique=False)
    op.create_table('employee_competencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('competency_id', sa.UUID(), nullable=False),
    sa.Column('current_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('confidence_label', sa.String(length=50), nullable=False),
    sa.Column('last_assessed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'competency_id', name='uq_employee_competency')
    )
    op.create_index(op.f('ix_employee_competencies_competency_id'), 'employee_competencies', ['competency_id'], unique=False)
    op.create_index(op.f('ix_employee_competencies_employee_id'), 'employee_competencies', ['employee_id'], unique=False)
    op.create_table('assessment_responses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('selected_option', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('points_earned', sa.Float(), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['assessment_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['assessment_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'question_id', name='uq_attempt_question')
    )
    op.create_index(op.f('ix_assessment_responses_attempt_id'), 'assessment_responses', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_assessment_responses_question_id'), 'assessment_responses', ['question_id'], unique=False)
    op.create_table('competency_score_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('competency_id', sa.UUID(), nullable=False),
    sa.Column('previous_score', sa.Float(), nullable=True),
    sa.Column('new_score', sa.Float(), nullable=False),
    sa.Column('previous_confidence', sa.Float(), nullable=True),
    sa.Column('new_confidence', sa.Float(), nullable=False),
    sa.Column('trigger_evidence_id', sa.UUID(), nullable=True),
    sa.Column('change_reason', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trigger_evidence_id'], ['competency_evidence.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competency_score_history_competency_id'), 'competency_score_history', ['competency_id'], unique=False)
    op.create_index(op.f('ix_competency_score_history_employee_id'), 'competency_score_history', ['employee_id'], unique=False)
    op.add_column('training_history', sa.Column('competency_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_training_history_competency_id'), 'training_history', ['competency_id'], unique=False)
    op.create_foreign_key(None, 'training_history', 'competencies', ['competency_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'training_history', type_='foreignkey')
    op.drop_index(op.f('ix_training_history_competency_id'), table_name='training_history')
    op.drop_column('training_history', 'competency_id')
    op.drop_index(op.f('ix_competency_score_history_employee_id'), table_name='competency_score_history')
    op.drop_index(op.f('ix_competency_score_history_competency_id'), table_name='competency_score_history')
    op.drop_table('competency_score_history')
    op.drop_index(op.f('ix_assessment_responses_question_id'), table_name='assessment_responses')
    op.drop_index(op.f('ix_assessment_responses_attempt_id'), table_name='assessment_responses')
    op.drop_table('assessment_responses')
    op.drop_index(op.f('ix_employee_competencies_employee_id'), table_name='employee_competencies')
    op.drop_index(op.f('ix_employee_competencies_competency_id'), table_name='employee_competencies')
    op.drop_table('employee_competencies')
    op.drop_index(op.f('ix_competency_evidence_evidence_type'), table_name='competency_evidence')
    op.drop_index(op.f('ix_competency_evidence_employee_id'), table_name='competency_evidence')
    op.drop_index(op.f('ix_competency_evidence_competency_id'), table_name='competency_evidence')
    op.drop_table('competency_evidence')
    op.drop_index(op.f('ix_assessment_questions_competency_id'), table_name='assessment_questions')
    op.drop_index(op.f('ix_assessment_questions_assessment_id'), table_name='assessment_questions')
    op.drop_table('assessment_questions')
    op.drop_index(op.f('ix_assessment_competencies_competency_id'), table_name='assessment_competencies')
    op.drop_index(op.f('ix_assessment_competencies_assessment_id'), table_name='assessment_competencies')
    op.drop_table('assessment_competencies')
    op.drop_index(op.f('ix_assessment_attempts_employee_id'), table_name='assessment_attempts')
    op.drop_index(op.f('ix_assessment_attempts_assessment_id'), table_name='assessment_attempts')
    op.drop_table('assessment_attempts')
    op.drop_table('assessments')
    # ### end Alembic commands ###
