"""create_competency_framework_tables

Revision ID: b10fc32ecd4c
Revises: 8855071b48b4
Create Date: 2026-09-12 10:58:47.916295

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b10fc32ecd4c'
down_revision: str | Sequence[str] | None = '8855071b48b4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competency_domains',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('courses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_code')
    )
    op.create_table('proficiency_levels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('level_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('minimum_score', sa.Integer(), nullable=False),
    sa.Column('maximum_score', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('level_number')
    )
    op.create_table('training_programmes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('programme_code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('programme_code')
    )
    op.create_table('competencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('domain_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('short_description', sa.String(length=255), nullable=False),
    sa.Column('learning_objectives', sa.Text(), nullable=True),
    sa.Column('measurement_guidance', sa.Text(), nullable=True),
    sa.Column('aliases', sa.String(length=255), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('source_reference', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['competency_domains.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['competencies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_competencies_code'), 'competencies', ['code'], unique=True)
    op.create_index(op.f('ix_competencies_domain_id'), 'competencies', ['domain_id'], unique=False)
    op.create_table('competency_relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_competency_id', sa.UUID(), nullable=False),
    sa.Column('target_competency_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_competency_id'], ['competencies.id'], ),
    sa.ForeignKeyConstraint(['target_competency_id'], ['competencies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competency_relationships_source_competency_id'), 'competency_relationships', ['source_competency_id'], unique=False)
    op.create_index(op.f('ix_competency_relationships_target_competency_id'), 'competency_relationships', ['target_competency_id'], unique=False)
    op.create_table('competency_requirements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_role_id', sa.UUID(), nullable=False),
    sa.Column('competency_id', sa.UUID(), nullable=False),
    sa.Column('required_level_id', sa.UUID(), nullable=False),
    sa.Column('required_score', sa.Integer(), nullable=False),
    sa.Column('criticality', sa.String(length=20), nullable=False),
    sa.Column('task_relevance', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('source_reference', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ),
    sa.ForeignKeyConstraint(['job_role_id'], ['job_roles.id'], ),
    sa.ForeignKeyConstraint(['required_level_id'], ['proficiency_levels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_role_id', 'competency_id', name='uq_role_competency')
    )
    op.create_index(op.f('ix_competency_requirements_competency_id'), 'competency_requirements', ['competency_id'], unique=False)
    op.create_index(op.f('ix_competency_requirements_job_role_id'), 'competency_requirements', ['job_role_id'], unique=False)
    op.create_index(op.f('ix_competency_requirements_required_level_id'), 'competency_requirements', ['required_level_id'], unique=False)
    op.create_table('course_competencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('competency_id', sa.UUID(), nullable=False),
    sa.Column('coverage_level', sa.String(length=50), nullable=False),
    sa.Column('learning_outcome', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_competencies_competency_id'), 'course_competencies', ['competency_id'], unique=False)
    op.create_index(op.f('ix_course_competencies_course_id'), 'course_competencies', ['course_id'], unique=False)
    op.create_table('training_programme_competencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('training_programme_id', sa.UUID(), nullable=False),
    sa.Column('competency_id', sa.UUID(), nullable=False),
    sa.Column('coverage_level', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['training_programme_id'], ['training_programmes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_programme_competencies_competency_id'), 'training_programme_competencies', ['competency_id'], unique=False)
    op.create_index(op.f('ix_training_programme_competencies_training_programme_id'), 'training_programme_competencies', ['training_programme_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_programme_competencies_training_programme_id'), table_name='training_programme_competencies')
    op.drop_index(op.f('ix_training_programme_competencies_competency_id'), table_name='training_programme_competencies')
    op.drop_table('training_programme_competencies')
    op.drop_index(op.f('ix_course_competencies_course_id'), table_name='course_competencies')
    op.drop_index(op.f('ix_course_competencies_competency_id'), table_name='course_competencies')
    op.drop_table('course_competencies')
    op.drop_index(op.f('ix_competency_requirements_required_level_id'), table_name='competency_requirements')
    op.drop_index(op.f('ix_competency_requirements_job_role_id'), table_name='competency_requirements')
    op.drop_index(op.f('ix_competency_requirements_competency_id'), table_name='competency_requirements')
    op.drop_table('competency_requirements')
    op.drop_index(op.f('ix_competency_relationships_target_competency_id'), table_name='competency_relationships')
    op.drop_index(op.f('ix_competency_relationships_source_competency_id'), table_name='competency_relationships')
    op.drop_table('competency_relationships')
    op.drop_index(op.f('ix_competencies_domain_id'), table_name='competencies')
    op.drop_index(op.f('ix_competencies_code'), table_name='competencies')
    op.drop_table('competencies')
    op.drop_table('training_programmes')
    op.drop_table('proficiency_levels')
    op.drop_table('courses')
    op.drop_table('competency_domains')
    # ### end Alembic commands ###
