"""
PRAGYA STAGE 7 — SYNTHETIC LEARNING CATALOGUE (PROTOTYPE DEMONSTRATION)
DISCLAIMER:
All records below are synthetic/mock demonstration records for testing the PRAGYA
Personalized Learning Recommendation Engine. They do not constitute official government
course lists or active live APIs from iGOT Karmayogi or NSSTA.
"""

SYNTHETIC_LEARNING_ITEMS = [
    # =========================================================================
    # iGOT KARMAYOGI (MOCK DIGITAL COURSES) — 22 ITEMS
    # =========================================================================
    {
        "provider": "IGOT",
        "provider_item_id": "IGOT-STAT-001",
        "title": "Foundations of Survey Sampling & Frame Construction",
        "description": "Comprehensive digital course on probability sampling techniques, stratification strategies, sampling frames, and standard error estimation for official surveys.",
        "type": "COURSE",
        "difficulty": "BEGINNER",
        "level": 2,
        "duration_minutes": 180,
        "language": "English",
        "format": "SELF_PACED",
        "url": None,
        "prerequisites": [],
        "competencies": [
            {"competency_code": "STAT_SAMPLING", "coverage_level": "FOUNDATION", "learning_outcome": "Understand probability sampling, stratification, and sample size determination."},
            {"competency_code": "STAT_SURVEY_DESIGN", "coverage_level": "INTRODUCTORY", "learning_outcome": "Frame selection and sampling schedule design."},
            {"competency_code": "STAT_AGRICULTURAL_STATISTICS", "coverage_level": "FOUNDATION", "learning_outcome": "Construct crop area and agricultural holding sampling frames."},
        ],
    },
    {
        "provider": "IGOT",
        "provider_item_id": "IGOT-STAT-002",
        "title": "Advanced Multi-Stage Stratified Sampling in Practice",
        "description": "Hands-on survey sampling covering cluster sampling, multi-stage sample allocation, PPS sampling, and weighting adjustment factors in large-scale socio-economic surveys.",
        "type": "COURSE",
        "difficulty": "INTERMEDIATE",
        "level": 3,
        "duration_minutes": 240,
        "language": "English",
        "format": "SELF_PACED",
        "url": None,
        "prerequisites": [{"competency_code": "STAT_SAMPLING", "min_score": 30.0}],
        "competencies": [
            {"competency_code": "STAT_SAMPLING", "coverage_level": "WORKING", "learning_outcome": "Implement multi-stage probability proportionate to size (PPS) sampling."},
            {"competency_code": "STAT_SURVEY_DESIGN", "coverage_level": "WORKING", "learning_outcome": "Determine sample size and design weights for multi-round surveys."},
        ],
    },
    {
        "provider": "IGOT",
        "provider_item_id": "IGOT-STAT-003",
        "title": "Survey Questionnaire Design & Cognitive Testing",
        "description": "Techniques for designing clear, unbiased questionnaires, schedule design, skip patterns, and conducting cognitive pre-testing for national household surveys.",
        "type": "COURSE",
        "difficulty": "BEGINNER",
        "level": 2,
        "duration_minutes": 150,
        "language": "English",
        "format": "SELF_PACED",
        "url": None,
        "prerequisites": [],
        "competencies": [
            {"competency_code": "STAT_SURVEY_DESIGN", "coverage_level": "FOUNDATION", "learning_outcome": "Formulate valid survey questions, schedules, and response options."},
            {"competency_code": "BEHAVIOR_COMMUNICATION", "coverage_level": "INTRODUCTORY", "learning_outcome": "Communicate complex inquiries effectively to field respondents."},
        ],
    },
    {
        "provider": "IGOT",
        "provider_item_id": "IGOT-STAT-004",
        "title": "National Sample Survey Field Methodology & Validation",
        "description": "Standardized field survey operational guidelines, respondent contact protocols, non-response mitigation, and field-level data validation procedures.",
        "type": "COURSE",
        "difficulty": "INTERMEDIATE",
        "level": 3,
        "duration_minutes": 210,
        "language": "English",
        "format": "SELF_PACED",
        "url": None,
        "prerequisites": [],
        "competencies": [
            {"competency_code": "STAT_SURVEY_DESIGN", "coverage_level": "WORKING", "learning_outcome": "Oversee field operations, resolve non-response, and enforce schedule protocols."},
            {"competency_code": "STAT_DATA_QUALITY_FRAMEWORKS", "coverage_level": "WORKING", "learning_outcome": "Detect field anomalies and enforce consistency checks."},
            {"competency_code": "STAT_LABOUR_STATISTICS", "coverage_level": "WORKING", "learning_outcome": "Oversee Periodic Labour Force Survey (PLFS) schedules and employment classifications."},
        ],
    },
    {
        "provider": "IGOT",
        "provider_item_id": "IGOT-STAT-005",
        "title": "Data Quality Assurance Frameworks for National Statistics",
        "description": "Principles of the UN National Quality Assurance Framework (NQAF), data editing, imputation methods, consistency checks, and audit trails.",
        "type": "COURSE",
        "difficulty": "INTERMEDIATE",
        "level": 3,
        "duration_minutes": 180,
        "language": "English",
        "format": "SELF_PACED",
        "url": None,
        "prerequisites": [],
        "competencies": [
            {"competency_code": "STAT_DATA_QUALITY_FRAMEWORKS", "coverage_level": "WORKING", "learning_outcome": "Apply NQAF principles and automated data editing rules."},
        ],
    },
    {
        "provider": "IGOT",
        "provider_item_id": "IGOT-STAT-006",
        "title": "Advanced Data Imputation & Outlier Detection",
        "description": "Statistical methods for donor imputation, regression imputation, outlier bounding, and robust variance estimation in economic microdata.",
        "type": "COURSE",
        "difficulty": "ADVANCED",
        "level": 4,
        "duration_minutes": 270,
        "language": "English",
        "format": "SELF_PACED",
        "url": None,
        "prerequisites": [{"competency_code": "STAT_DATA_QUALITY_FRAMEWORKS", "min_score": 40.0}],
        "competencies": [
            {"competency_code": "STAT_DATA_QUALITY_FRAMEWORKS", "coverage_level": "ADVANCED", "learning_outcome": "Execute cold-deck, hot-deck, and regression imputation."},
            {"competency_code": "STAT_SAMPLING", "coverage_level": "WORKING", "learning_outcome": "Evaluate non-response bias and variance inflation."},
        ],
    },
    {
        "provider": "IGOT",
        "provider_item_id": "IGOT-TECH-001",
        "title": "Python for Statistical Data Processing & Analysis",
        "description": "Foundational Python for official statistics using pandas, numpy, and Jupyter notebooks for survey data manipulation, cleaning, and summary tabulation.",
        "type": "COURSE",
        "difficulty": "BEGINNER",
        "level": 2,
        "duration_minutes": 240,
        "language": "English",
        "format": "SELF_PACED",
        "url": None,
        "prerequisites": [],
        "competencies": [
            {"competency_code": "TECH_PYTHON", "coverage_level": "FOUNDATION", "learning_outcome": "Manipulate tabular dataframes and compute weighted statistical summaries."},
        ],
    },
    {
        "provider": "IGOT",
        "provider_item_id": "IGOT-TECH-002",
        "title": "Intermediate Python: Automated Microdata Pipelines",
        "description": "Building reproducible ETL pipelines, automated validation scripts, data parsing, and unit testing for national socio-economic datasets.",
        "type": "COURSE",
        "difficulty": "INTERMEDIATE",
        "level": 3,
        "duration_minutes": 300,
        "language": "English",
        "format": "SELF_PACED",
        "url": None,
        "prerequisites": [{"competency_code": "TECH_PYTHON", "min_score": 25.0}],
        "competencies": [
            {"competency_code": "TECH_PYTHON", "coverage_level": "WORKING", "learning_outcome": "Construct modular data pipelines and automated quality checks."},
            {"competency_code": "STAT_DATA_QUALITY_FRAMEWORKS", "coverage_level": "WORKING", "learning_outcome": "Automate consistency checks across multi-table surveys."},
        ],
    },
    {
        "provider": "IGOT",
        "provider_item_id": "IGOT-TECH-003",
        "title": "Relational Databases & SQL for Survey Microdata",
        "description": "SQL querying essentials, joins, aggregate functions, indexing, and querying multi-round enterprise and household survey databases.",
        "type": "COURSE",
        "difficulty": "BEGINNER",
        "level": 2,
        "duration_minutes": 180,
        "language": "English",
        "format": "SELF_PACED",
        "url": None,
        "prerequisites": [],
        "competencies": [
            {"competency_code": "TECH_SQL", "coverage_level": "FOUNDATION", "learning_outcome": "Query, join, and aggregate normalized statistical relational tables."},
        ],
    },
    {
        "provider": "IGOT",
        "provider_item_id": "IGOT-TECH-004",
        "title": "Advanced SQL & Database Optimization for Statistical Aggregation",
        "description": "Window functions, common table expressions (CTEs), partitioning, and query optimization for billion-row administrative records.",
        "type": "COURSE",
        "difficulty": "ADVANCED",
        "level": 4,
        "duration_minutes": 270,
        "language": "English",
        "format": "SELF_PACED",
        "url": None,
        "prerequisites": [{"competency_code": "TECH_SQL", "min_score": 40.0}],
        "competencies": [
            {"competency_code": "TECH_SQL", "coverage_level": "ADVANCED", "learning_outcome": "Write complex analytical window queries and optimize high-volume database views."},
        ],
    },
    {
        "provider": "IGOT",
        "provider_item_id": "IGOT-TECH-005",
        "title": "Introduction to Geographic Information Systems (GIS) for Official Statistics",
        "description": "Geospatial mapping fundamentals, shapefile handling, spatial joins, and thematic map creation for census enumeration blocks.",
        "type": "COURSE",
        "difficulty": "BEGINNER",
        "level": 2,
        "duration_minutes": 180,
        "language": "English",
        "format": "SELF_PACED",
        "url": None,
        "prerequisites": [],
        "competencies": [
            {"competency_code": "TECH_GIS", "coverage_level": "FOUNDATION", "learning_outcome": "Visualize spatial census blocks and create thematic choropleth maps."},
            {"competency_code": "TECH_DATA_VISUALIZATION", "coverage_level": "INTRODUCTORY", "learning_outcome": "Design cartographic presentations of demographic data."},
        ],
    },
    {
        "provider": "IGOT",
        "provider_item_id": "IGOT-TECH-006",
        "title": "Spatial Analysis & Geocoding for Survey Operations",
        "description": "Advanced geospatial analytics, buffer zones, spatial cluster detection, and GPS-enabled field survey auditing using open-source QGIS and GeoPandas.",
        "type": "COURSE",
        "difficulty": "INTERMEDIATE",
        "level": 3,
        "duration_minutes": 240,
        "language": "English",
        "format": "SELF_PACED",
        "url": None,
        "prerequisites": [{"competency_code": "TECH_GIS", "min_score": 25.0}],
        "competencies": [
            {"competency_code": "TECH_GIS", "coverage_level": "WORKING", "learning_outcome": "Perform spatial joins and trace GPS survey audit tracks."},
            {"competency_code": "TECH_PYTHON", "coverage_level": "WORKING", "learning_outcome": "Utilize GeoPandas for automated geospatial processing."},
        ],
    },
    {
        "provider": "IGOT",
        "provider_item_id": "IGOT-TECH-007",
        "title": "Interactive Data Visualization for Policy Insights",
        "description": "Visual design principles, dashboard design, color palettes, chart selection, and communicative visual storytelling for public statistical dissemination.",
        "type": "COURSE",
        "difficulty": "BEGINNER",
        "level": 2,
        "duration_minutes": 150,
        "language": "English",
        "format": "SELF_PACED",
        "url": None,
        "prerequisites": [],
        "competencies": [
            {"competency_code": "TECH_DATA_VISUALIZATION", "coverage_level": "FOUNDATION", "learning_outcome": "Create accessible, clear charts and summary dashboards."},
            {"competency_code": "BEHAVIOR_COMMUNICATION", "coverage_level": "INTRODUCTORY", "learning_outcome": "Translate complex statistical figures into visual narratives."},
        ],
    },
    {
        "provider": "IGOT",
        "provider_item_id": "IGOT-TECH-008",
        "title": "Advanced Charting & Dissemination Portals",
        "description": "Interactive web-based charts using D3/Plotly, SVG optimization, and WCAG accessibility standards for public statistical portals.",
        "type": "COURSE",
        "difficulty": "INTERMEDIATE",
        "level": 3,
        "duration_minutes": 210,
        "language": "English",
        "format": "SELF_PACED",
        "url": None,
        "prerequisites": [],
        "competencies": [
            {"competency_code": "TECH_DATA_VISUALIZATION", "coverage_level": "WORKING", "learning_outcome": "Build interactive drill-down charts for state and district indicators."},
        ],
    },
    {
        "provider": "IGOT",
        "provider_item_id": "IGOT-ETH-001",
        "title": "Ethics & Confidentiality in Official Statistics",
        "description": "Legal frameworks, Collection of Statistics Act, data confidentiality, anonymization protocols, and professional codes of conduct for statisticians.",
        "type": "COURSE",
        "difficulty": "BEGINNER",
        "level": 2,
        "duration_minutes": 120,
        "language": "English",
        "format": "SELF_PACED",
        "url": None,
        "prerequisites": [],
        "competencies": [
            {"competency_code": "BEHAVIOR_ETHICS", "coverage_level": "FOUNDATION", "learning_outcome": "Uphold statutory confidentiality and prevent microdata leakage."},
        ],
    },
    {
        "provider": "IGOT",
        "provider_item_id": "IGOT-ETH-002",
        "title": "Statistical Disclosure Control & Microdata Anonymization",
        "description": "Differential privacy, k-anonymity, l-diversity, perturbation techniques, and cell suppression for public microdata releases.",
        "type": "COURSE",
        "difficulty": "INTERMEDIATE",
        "level": 3,
        "duration_minutes": 180,
        "language": "English",
        "format": "SELF_PACED",
        "url": None,
        "prerequisites": [],
        "competencies": [
            {"competency_code": "BEHAVIOR_ETHICS", "coverage_level": "WORKING", "learning_outcome": "Apply k-anonymity algorithms and statistical disclosure controls."},
            {"competency_code": "STAT_DATA_QUALITY_FRAMEWORKS", "coverage_level": "WORKING", "learning_outcome": "Balance data utility against disclosure risk."},
        ],
    },
    {
        "provider": "IGOT",
        "provider_item_id": "IGOT-COMM-001",
        "title": "Effective Communication of Statistical Insights to Policymakers",
        "description": "Drafting policy briefs, executive summaries, managing media briefings, and presenting statistical uncertainty to non-specialist leadership.",
        "type": "COURSE",
        "difficulty": "BEGINNER",
        "level": 2,
        "duration_minutes": 150,
        "language": "English",
        "format": "SELF_PACED",
        "url": None,
        "prerequisites": [],
        "competencies": [
            {"competency_code": "BEHAVIOR_COMMUNICATION", "coverage_level": "FOUNDATION", "learning_outcome": "Draft clear statistical notes and briefs for administrative leaders."},
        ],
    },
    {
        "provider": "IGOT",
        "provider_item_id": "IGOT-COMM-002",
        "title": "Inter-Agency Statistical Coordination & Reporting",
        "description": "Collaborative reporting frameworks, state statistical coordination, multi-department data harmonization, and technical documentation.",
        "type": "COURSE",
        "difficulty": "INTERMEDIATE",
        "level": 3,
        "duration_minutes": 180,
        "language": "English",
        "format": "SELF_PACED",
        "url": None,
        "prerequisites": [],
        "competencies": [
            {"competency_code": "BEHAVIOR_COMMUNICATION", "coverage_level": "WORKING", "learning_outcome": "Lead technical working groups and synchronize cross-departmental datasets."},
        ],
    },
    {
        "provider": "IGOT",
        "provider_item_id": "IGOT-DIGI-001",
        "title": "Digital Governance & Citizen Data Rights",
        "description": "Digital Personal Data Protection Act (DPDP), digital governance architectures, government data open standards, and public register management.",
        "type": "COURSE",
        "difficulty": "BEGINNER",
        "level": 2,
        "duration_minutes": 150,
        "language": "English",
        "format": "SELF_PACED",
        "url": None,
        "prerequisites": [],
        "competencies": [
            {"competency_code": "DIGITAL_DATA_PRIVACY", "coverage_level": "FOUNDATION", "learning_outcome": "Implement DPDP compliance and manage open data mandates."},
        ],
    },
    {
        "provider": "IGOT",
        "provider_item_id": "IGOT-DIGI-002",
        "title": "Metadata Architecture & National Data Exchange Standards",
        "description": "SDMX standards, DDI standards, Dublin Core metadata, and automated API exchange protocols across national statistical databases.",
        "type": "COURSE",
        "difficulty": "INTERMEDIATE",
        "level": 3,
        "duration_minutes": 210,
        "language": "English",
        "format": "SELF_PACED",
        "url": None,
        "prerequisites": [],
        "competencies": [
            {"competency_code": "DIGITAL_DATA_PRIVACY", "coverage_level": "WORKING", "learning_outcome": "Standardize statistical tables with SDMX schemas."},
        ],
    },
    {
        "provider": "IGOT",
        "provider_item_id": "IGOT-LEAD-001",
        "title": "Leadership & Project Management for Field Survey Teams",
        "description": "Field investigator deployment, operational timeline tracking, team conflict resolution, and quality audit supervision in large statistical surveys.",
        "type": "COURSE",
        "difficulty": "INTERMEDIATE",
        "level": 3,
        "duration_minutes": 210,
        "language": "English",
        "format": "SELF_PACED",
        "url": None,
        "prerequisites": [],
        "competencies": [
            {"competency_code": "BEHAVIOR_LEADERSHIP", "coverage_level": "WORKING", "learning_outcome": "Manage multi-district survey squads and meet rigorous delivery timelines."},
        ],
    },
    {
        "provider": "IGOT",
        "provider_item_id": "IGOT-STAT-007",
        "title": "Economic Statistics & Price Index Compilation (CPI & WPI)",
        "description": "Methodology for Consumer Price Index (CPI), Wholesale Price Index (WPI), item basket selection, geometric price index formulas, and outlet replacement.",
        "type": "COURSE",
        "difficulty": "INTERMEDIATE",
        "level": 3,
        "duration_minutes": 240,
        "language": "English",
        "format": "SELF_PACED",
        "url": None,
        "prerequisites": [],
        "competencies": [
            {"competency_code": "STAT_PRICE_STATISTICS", "coverage_level": "WORKING", "learning_outcome": "Calculate Laspeyres and geometric price indices (CPI/WPI) and validate market price quotes."},
            {"competency_code": "STAT_DATA_QUALITY_FRAMEWORKS", "coverage_level": "WORKING", "learning_outcome": "Apply quality verification on price microdata."},
            {"competency_code": "STAT_SAMPLING", "coverage_level": "FOUNDATION", "learning_outcome": "Establish representative village and urban market price sample frames."},
        ],
    },

    # =========================================================================
    # NSSTA / TPAC (MOCK INSTITUTIONAL PROGRAMMES) — 11 ITEMS
    # =========================================================================
    {
        "provider": "NSSTA_TPAC",
        "provider_item_id": "NSSTA-PROG-101",
        "title": "Executive Workshop on Modern Survey Design & Execution",
        "description": "5-day residential institutional programme at NSSTA Greater Noida covering sample design, Computer Assisted Personal Interviewing (CAPI), and survey logistics.",
        "type": "PROGRAMME",
        "difficulty": "INTERMEDIATE",
        "level": 3,
        "duration_minutes": 1800,  # 30 hours
        "language": "English",
        "format": "INSTRUCTOR_LED",
        "url": "https://mock.nssta.gov.in/programmes/survey-design-executive",
        "prerequisites": [{"competency_code": "STAT_SURVEY_DESIGN", "min_score": 30.0}],
        "competencies": [
            {"competency_code": "STAT_SURVEY_DESIGN", "coverage_level": "WORKING", "learning_outcome": "Design end-to-end national survey schedules and supervise CAPI deployment."},
            {"competency_code": "STAT_SAMPLING", "coverage_level": "WORKING", "learning_outcome": "Calculate complex survey weights and sample design variance."},
        ],
    },
    {
        "provider": "NSSTA_TPAC",
        "provider_item_id": "NSSTA-PROG-102",
        "title": "Masterclass in Advanced Statistical Sampling & Small Area Estimation",
        "description": "Rigorous hands-on institutional workshop on small area estimation (SAE), Fay-Herriot models, empirical Bayes estimators, and sub-district statistical disaggregation.",
        "type": "PROGRAMME",
        "difficulty": "ADVANCED",
        "level": 4,
        "duration_minutes": 2400,  # 40 hours
        "language": "English",
        "format": "INSTRUCTOR_LED",
        "url": "https://mock.nssta.gov.in/programmes/small-area-estimation-masterclass",
        "prerequisites": [{"competency_code": "STAT_SAMPLING", "min_score": 50.0}],
        "competencies": [
            {"competency_code": "STAT_SAMPLING", "coverage_level": "ADVANCED", "learning_outcome": "Formulate small area models to generate reliable district and block-level estimates."},
        ],
    },
    {
        "provider": "NSSTA_TPAC",
        "provider_item_id": "NSSTA-PROG-103",
        "title": "Institutional Workshop on Official Statistics Quality Auditing",
        "description": "Practical training on implementing the MoSPI Quality Audit Framework, re-interviewing audits, supervisor inspections, and statistical discrepancy analysis.",
        "type": "PROGRAMME",
        "difficulty": "INTERMEDIATE",
        "level": 3,
        "duration_minutes": 1200,  # 20 hours
        "language": "English",
        "format": "INSTRUCTOR_LED",
        "url": "https://mock.nssta.gov.in/programmes/quality-auditing-workshop",
        "prerequisites": [],
        "competencies": [
            {"competency_code": "STAT_DATA_QUALITY_FRAMEWORKS", "coverage_level": "WORKING", "learning_outcome": "Conduct quality audits and compute response consistency ratios."},
            {"competency_code": "BEHAVIOR_ETHICS", "coverage_level": "WORKING", "learning_outcome": "Enforce strict ethical audit benchmarks across regional offices."},
        ],
    },
    {
        "provider": "NSSTA_TPAC",
        "provider_item_id": "NSSTA-PROG-104",
        "title": "Advanced Geospatial Technologies in Census & Survey Planning",
        "description": "Intensive laboratory on satellite imagery integration, boundary harmonization, GPS field validation, and digital enumeration mapping.",
        "type": "PROGRAMME",
        "difficulty": "ADVANCED",
        "level": 4,
        "duration_minutes": 1500,  # 25 hours
        "language": "English",
        "format": "BLENDED",
        "url": "https://mock.nssta.gov.in/programmes/geospatial-census-technologies",
        "prerequisites": [{"competency_code": "TECH_GIS", "min_score": 35.0}],
        "competencies": [
            {"competency_code": "TECH_GIS", "coverage_level": "ADVANCED", "learning_outcome": "Direct GIS-based census boundary delineation and drone/satellite spatial audits."},
        ],
    },
    {
        "provider": "NSSTA_TPAC",
        "provider_item_id": "NSSTA-PROG-105",
        "title": "Python & Big Data Engineering for Official Statistics",
        "description": "Training programme for Indian Statistical Service officers on distributed computing, PySpark, API-driven data collection, and web scraping for statistical compilation.",
        "type": "PROGRAMME",
        "difficulty": "ADVANCED",
        "level": 4,
        "duration_minutes": 2100,  # 35 hours
        "language": "English",
        "format": "INSTRUCTOR_LED",
        "url": "https://mock.nssta.gov.in/programmes/python-big-data-engineering",
        "prerequisites": [{"competency_code": "TECH_PYTHON", "min_score": 40.0}],
        "competencies": [
            {"competency_code": "TECH_PYTHON", "coverage_level": "ADVANCED", "learning_outcome": "Build scalable data pipelines processing multi-gigabyte administrative records."},
            {"competency_code": "TECH_SQL", "coverage_level": "WORKING", "learning_outcome": "Integrate SQL data warehouses with Python analytics engines."},
        ],
    },
    {
        "provider": "NSSTA_TPAC",
        "provider_item_id": "NSSTA-PROG-106",
        "title": "National Accounts & Gross State Domestic Product (GSDP) Compilation",
        "description": "System of National Accounts (SNA 2008) methodology, GSDP estimation by economic activity, double deflation, and inter-state trade reconciliation.",
        "type": "PROGRAMME",
        "difficulty": "ADVANCED",
        "level": 4,
        "duration_minutes": 2400,  # 40 hours
        "language": "English",
        "format": "INSTRUCTOR_LED",
        "url": "https://mock.nssta.gov.in/programmes/national-accounts-gsdp",
        "prerequisites": [],
        "competencies": [
            {"competency_code": "STAT_NATIONAL_ACCOUNTS", "coverage_level": "ADVANCED", "learning_outcome": "System of National Accounts (SNA 2008) compilation, gross domestic product estimation, and macroeconomic aggregates."},
            {"competency_code": "STAT_DATA_QUALITY_FRAMEWORKS", "coverage_level": "ADVANCED", "learning_outcome": "Validate macroeconomic aggregates and resolve statistical discrepancies in GSDP."},
            {"competency_code": "BEHAVIOR_COMMUNICATION", "coverage_level": "WORKING", "learning_outcome": "Present national accounts releases to economic advisory committees."},
        ],
    },
    {
        "provider": "NSSTA_TPAC",
        "provider_item_id": "NSSTA-PROG-107",
        "title": "Leadership & Cadre Management for Statistical Officers",
        "description": "Executive capacity development focusing on civil service values, administrative ethics, cadre management, and mentoring junior statistical personnel.",
        "type": "PROGRAMME",
        "difficulty": "INTERMEDIATE",
        "level": 3,
        "duration_minutes": 900,  # 15 hours
        "language": "English",
        "format": "INSTRUCTOR_LED",
        "url": "https://mock.nssta.gov.in/programmes/cadre-management-leadership",
        "prerequisites": [],
        "competencies": [
            {"competency_code": "BEHAVIOR_LEADERSHIP", "coverage_level": "WORKING", "learning_outcome": "Mentor field statisticians and direct high-performance survey divisions."},
            {"competency_code": "BEHAVIOR_ETHICS", "coverage_level": "WORKING", "learning_outcome": "Instill ethical civil service norms across field offices."},
        ],
    },
    {
        "provider": "NSSTA_TPAC",
        "provider_item_id": "NSSTA-PROG-108",
        "title": "Data Governance, Classification Systems & National Standards",
        "description": "NIC-2008, NCO-2015, product classifications, and implementing national metadata registries in state statistical bureaus.",
        "type": "PROGRAMME",
        "difficulty": "INTERMEDIATE",
        "level": 3,
        "duration_minutes": 1200,  # 20 hours
        "language": "English",
        "format": "BLENDED",
        "url": "https://mock.nssta.gov.in/programmes/data-governance-classifications",
        "prerequisites": [],
        "competencies": [
            {"competency_code": "DIGITAL_DATA_PRIVACY", "coverage_level": "WORKING", "learning_outcome": "Map survey response items to canonical national industrial classifications."},
        ],
    },
    {
        "provider": "NSSTA_TPAC",
        "provider_item_id": "NSSTA-PROG-109",
        "title": "Statistical Writing, Briefing & Media Engagement",
        "description": "Preparing press releases, statistical yearbooks, parliamentary question responses, and managing public data inquiries with clarity and precision.",
        "type": "PROGRAMME",
        "difficulty": "INTERMEDIATE",
        "level": 3,
        "duration_minutes": 900,  # 15 hours
        "language": "English",
        "format": "INSTRUCTOR_LED",
        "url": "https://mock.nssta.gov.in/programmes/statistical-writing-briefing",
        "prerequisites": [],
        "competencies": [
            {"competency_code": "BEHAVIOR_COMMUNICATION", "coverage_level": "WORKING", "learning_outcome": "Draft parliamentary replies and official statistical press briefings."},
        ],
    },
    {
        "provider": "NSSTA_TPAC",
        "provider_item_id": "NSSTA-PROG-110",
        "title": "Applied Index Numbers & High-Frequency Economic Indicators",
        "description": "Index of Industrial Production (IIP), seasonal adjustments, chain-linking methods, and compiling high-frequency economic monitors.",
        "type": "PROGRAMME",
        "difficulty": "INTERMEDIATE",
        "level": 3,
        "duration_minutes": 1500,  # 25 hours
        "language": "English",
        "format": "INSTRUCTOR_LED",
        "url": "https://mock.nssta.gov.in/programmes/index-numbers-iip",
        "prerequisites": [],
        "competencies": [
            {"competency_code": "STAT_DATA_QUALITY_FRAMEWORKS", "coverage_level": "WORKING", "learning_outcome": "Compute chained index numbers and apply seasonal adjustments."},
        ],
    },
    {
        "provider": "NSSTA_TPAC",
        "provider_item_id": "NSSTA-PROG-111",
        "title": "Foundational Survey Operations for Direct Recruits",
        "description": "Induction training for statistical officers covering the statutory foundation of the National Statistical System, schedule administration, and field ethics.",
        "type": "PROGRAMME",
        "difficulty": "BEGINNER",
        "level": 2,
        "duration_minutes": 1800,  # 30 hours
        "language": "English",
        "format": "INSTRUCTOR_LED",
        "url": "https://mock.nssta.gov.in/programmes/induction-survey-operations",
        "prerequisites": [],
        "competencies": [
            {"competency_code": "STAT_SURVEY_DESIGN", "coverage_level": "FOUNDATION", "learning_outcome": "Navigate official schedule structures and understand survey logistics."},
            {"competency_code": "BEHAVIOR_ETHICS", "coverage_level": "FOUNDATION", "learning_outcome": "Adhere strictly to official conduct rules and data secrecy regulations."},
        ],
    },

    # =========================================================================
    # PRAGYA INTERNAL LEARNING & INTERACTIVE LABS — 7 ITEMS
    # =========================================================================
    {
        "provider": "PRAGYA",
        "provider_item_id": "PRAGYA-LAB-001",
        "title": "PRAGYA Interactive Survey Design & Schedule Simulator",
        "description": "Hands-on virtual simulation lab allowing officers to design survey schedules, test skip logic branching, and simulate respondent interaction scenarios.",
        "type": "LAB",
        "difficulty": "INTERMEDIATE",
        "level": 3,
        "duration_minutes": 90,
        "language": "English",
        "format": "INTERACTIVE_LAB",
        "url": "https://pragya.gov.in/labs/survey-design-simulator",
        "prerequisites": [],
        "competencies": [
            {"competency_code": "STAT_SURVEY_DESIGN", "coverage_level": "WORKING", "learning_outcome": "Configure skip logic, response validations, and evaluate schedule flow."},
        ],
    },
    {
        "provider": "PRAGYA",
        "provider_item_id": "PRAGYA-LAB-002",
        "title": "PRAGYA Sample Frame & Weighting Sandbox",
        "description": "Interactive web sandbox where officers upload simulated population frames, apply stratification boundaries, and calculate expansion weights in real time.",
        "type": "LAB",
        "difficulty": "INTERMEDIATE",
        "level": 3,
        "duration_minutes": 120,
        "language": "English",
        "format": "INTERACTIVE_LAB",
        "url": "https://pragya.gov.in/labs/sampling-weights-sandbox",
        "prerequisites": [{"competency_code": "STAT_SAMPLING", "min_score": 25.0}],
        "competencies": [
            {"competency_code": "STAT_SAMPLING", "coverage_level": "WORKING", "learning_outcome": "Calculate strata allocations and verify multiplier weights in an interactive browser sandbox."},
        ],
    },
    {
        "provider": "PRAGYA",
        "provider_item_id": "PRAGYA-LAB-003",
        "title": "PRAGYA Automated Data Quality & Anomaly Diagnostic Sandbox",
        "description": "Microdata lab for executing automated rule engines, identifying impossible age/marital status combinations, and auditing statistical outliers.",
        "type": "LAB",
        "difficulty": "INTERMEDIATE",
        "level": 3,
        "duration_minutes": 90,
        "language": "English",
        "format": "INTERACTIVE_LAB",
        "url": "https://pragya.gov.in/labs/data-quality-diagnostic",
        "prerequisites": [],
        "competencies": [
            {"competency_code": "STAT_DATA_QUALITY_FRAMEWORKS", "coverage_level": "WORKING", "learning_outcome": "Debug validation rules and rectify logical inconsistencies in simulated survey microdata."},
        ],
    },
    {
        "provider": "PRAGYA",
        "provider_item_id": "PRAGYA-LAB-004",
        "title": "PRAGYA GIS Boundary Verification & Mapping Studio",
        "description": "Interactive browser-based mapping studio to verify enumeration block boundaries, fix topology errors, and inspect district boundary overlaps.",
        "type": "LAB",
        "difficulty": "INTERMEDIATE",
        "level": 3,
        "duration_minutes": 120,
        "language": "English",
        "format": "INTERACTIVE_LAB",
        "url": "https://pragya.gov.in/labs/gis-boundary-studio",
        "prerequisites": [],
        "competencies": [
            {"competency_code": "TECH_GIS", "coverage_level": "WORKING", "learning_outcome": "Audit geographical enumeration boundaries and fix topology discrepancies."},
        ],
    },
    {
        "provider": "PRAGYA",
        "provider_item_id": "PRAGYA-LAB-005",
        "title": "PRAGYA Python Statistical Playground",
        "description": "Cloud Jupyter workspace with preloaded MoSPI survey schemas for running standard error scripts, pandas transforms, and publishing reproducible charts.",
        "type": "LAB",
        "difficulty": "BEGINNER",
        "level": 2,
        "duration_minutes": 90,
        "language": "English",
        "format": "INTERACTIVE_LAB",
        "url": "https://pragya.gov.in/labs/python-playground",
        "prerequisites": [],
        "competencies": [
            {"competency_code": "TECH_PYTHON", "coverage_level": "FOUNDATION", "learning_outcome": "Write Python data wrangling scripts in an isolated browser environment."},
        ],
    },
    {
        "provider": "PRAGYA",
        "provider_item_id": "PRAGYA-LAB-006",
        "title": "PRAGYA SQL Microdata Query Sandbox",
        "description": "Interactive database terminal with mock NSSO multi-stage tables for practicing analytical queries, subqueries, and window functions.",
        "type": "LAB",
        "difficulty": "BEGINNER",
        "level": 2,
        "duration_minutes": 75,
        "language": "English",
        "format": "INTERACTIVE_LAB",
        "url": "https://pragya.gov.in/labs/sql-query-sandbox",
        "prerequisites": [],
        "competencies": [
            {"competency_code": "TECH_SQL", "coverage_level": "FOUNDATION", "learning_outcome": "Execute and optimize complex multi-table SQL queries against statistical schemas."},
        ],
    },
    {
        "provider": "PRAGYA",
        "provider_item_id": "PRAGYA-LAB-007",
        "title": "PRAGYA Statistical Ethics & Data Protection Case Studies",
        "description": "Scenario-based branching simulation testing decisions regarding respondent confidentiality, data leaks, and statutory disclosure protocols.",
        "type": "LAB",
        "difficulty": "BEGINNER",
        "level": 2,
        "duration_minutes": 60,
        "language": "English",
        "format": "INTERACTIVE_LAB",
        "url": "https://pragya.gov.in/labs/ethics-case-simulations",
        "prerequisites": [],
        "competencies": [
            {"competency_code": "BEHAVIOR_ETHICS", "coverage_level": "FOUNDATION", "learning_outcome": "Resolve ethical dilemmas under the Collection of Statistics Act through simulated decision branching."},
        ],
    },
]
